#GET
GET http://localhost:4004/odata/v4/employee/Employee?$expand=department,profileDetail,projects

###POST
POST http://localhost:4004/odata/v4/employee/Employee
Content-Type: application/json

{
  "name_firstName": "Allan",
  "name_lastName": "Border",
  "dob": "1982-09-13",
  "phoneNumber": 8998899889,
  "isPermanent": true,
  "salary": 95000,
  "joiningDate": "2014-07-16",
  "address_City": "Lucknow",
  "address_State": "UP",
  "address_ZipCode": 820943,
  "profileDetail": {
    "bio": "Proven track record in reducing external security attacks",
    "linkedinUrl": "https://linkedin.com/in/allan-border"
  },
  "department_deptId": "80060101-7c65-46db-a27d-baed52a68b2d",
  "projects": [
    {
      "projectName": "DIY Hovercraft",
      "startDate": "2017-07-04",
      "endDate": "2020-05-01"
    }
  ]  
}

# "projects": [
#     {
#       "projectName": "Movie Recommendation System",
#       "startDate": "2023-02-01",
#       "endDate": "2025-04-04"
#     }
#   ]

###PUT, Update Employee Records
PUT http://localhost:4004/odata/v4/employee/Employee/f38134fc-c46c-46bd-977f-2fe32ebc9675
Content-Type: application/json

{
  "salary" : 100000,
  "address_State" : "Uttarakhand"
}

###DELETE EMPLOYEE
DELETE http://localhost:4004/odata/v4/employee/Employee/4b0cc3c9-b14a-4a2a-bb5c-0aa188ff0f68


###GET ALL DEPARTMENTS
GET http://localhost:4004/odata/v4/employee/Departments

###CREATE NEW DEPARTMENT
POST http://localhost:4004/odata/v4/employee/Departments
Content-Type: application/json

{
  "name": "Global Logistics & Supply",
  "location": "Chicago - North Hub"
}

### DELETE DEPARTMENT
DELETE http://localhost:4004/odata/v4/employee/Departments/8491043d-10a4-4cf0-aa39-f6e00f1654c8


### Testing View1
GET http://localhost:4004/odata/v4/employee/PermanentEmployees

### Testing View2
GET http://localhost:4004/odata/v4/employee/PermanentEmployeesBySalary(minSalary=82000)/Set


###Testing Unbounded Function
GET http://localhost:4004/odata/v4/employee/getPermanentEmployees()

###Testing Bounded Function
GET http://localhost:4004/odata/v4/employee/Employee(3506f2ff-aa1d-4f19-ad8e-e09e6a5d4a55)/getTotalProjects()

###Testing Unbounded Action
POST http://localhost:4004/odata/v4/employee/deactivateEmployees

###Testing Bounded Action, End ongoing project
POST http://localhost:4004/odata/v4/employee/EmployeeProjects(626b51fc-10f6-43b2-84d4-cfd675e6187e)/endProject



### GET Employee Search Result
GET http://localhost:4004/odata/v4/employee/searchEmployees(query='75000')



### GET Employee Order by Salary in DESCENDING ORDER
GET http://localhost:4004/odata/v4/employee/getEmployeesBySalary

### GET Departments having more than two employees using GROUP BY
GET http://localhost:4004/odata/v4/employee/employeesPerDepartment

### GET INNER JOIN - Employees with Department
GET http://localhost:4004/odata/v4/employee/employeeWithDepartment

### LEFT JOIN - GET Emplpoyees with project
GET http://localhost:4004/odata/v4/employee/employeesWithProjects

### RIGHT JOIN - GET ongoing projects with employee name sorted by start date
GET http://localhost:4004/odata/v4/employee/activeProjects

### Full Oyter Join - Employees with or without projects also Projects with or without employees
GET http://localhost:4004/odata/v4/employee/employeesAndProjectsFullJoin


###getting result from a Context
http://localhost:4004/odata/v4/company/Valuations