#GET
GET http://localhost:4004/odata/v4/employee/Employee?$expand=department,profileDetail,projects

###POST
POST http://localhost:4004/odata/v4/employee/Employee
Content-Type: application/json

{
  "name_firstName": "Harry2",
  "name_lastName": "Potter2",
  "dob": "1992-10-03",
  "isPermanent": true,
  "salary": 75000,
  "joiningDate": "2021-03-23",
  "address_City": "Dehradun",
  "address_State": "Uttarakhan",
  "address_ZipCode": 560291,
  "profileDetail": {
    "bio": "Professional Lawyer",
    "linkedinUrl": "https://linkedin.com/in/demo7"
  },

  "department_deptId": "80060098-16c5-4b43-b25a-3faa4e1198ce"

  
}

# "projects": [
#     {
#       "projectName": "Movie Recommendation System",
#       "startDate": "2023-02-01",
#       "endDate": "2025-04-04"
#     }
#   ]

###PUT, Update Employee Records
PUT http://localhost:4004/odata/v4/employee/Employee/f38134fc-c46c-46bd-977f-2fe32ebc9675
Content-Type: application/json

{
  "salary" : 100000,
  "address_State" : "Uttarakhand"
}

###DELETE EMPLOYEE
DELETE http://localhost:4004/odata/v4/employee/Employee/b0b6e57d-ab62-42a7-8641-37c38b2bba1f



###GET ALL DEPARTMENTS
GET http://localhost:4004/odata/v4/employee/Departments

###CREATE NEW DEPARTMENT
POST http://localhost:4004/odata/v4/employee/Departments
Content-Type: application/json

{
  "name": "Global Logistics & Supply",
  "location": "Chicago - North Hub"
}

### DELETE DEPARTMENT
DELETE http://localhost:4004/odata/v4/employee/Departments/8491043d-10a4-4cf0-aa39-f6e00f1654c8


### Testing View1
GET http://localhost:4004/odata/v4/employee/PermanentEmployees

### Testing View2
GET http://localhost:4004/odata/v4/employee/PermanentEmployeesBySalary(minSalary=82000)/Set


###Testing Unbounded Function
GET http://localhost:4004/odata/v4/employee/getPermanentEmployees()

###Testing Bounded Function
GET http://localhost:4004/odata/v4/employee/Employee(3506f2ff-aa1d-4f19-ad8e-e09e6a5d4a55)/getTotalProjects()

###Testing Unbounded Action
POST http://localhost:4004/odata/v4/employee/deactivateEmployees

###Testing Bounded Action, End ongoing project
POST http://localhost:4004/odata/v4/employee/EmployeeProjects(cf310f22-9918-4cdd-858c-b2a2347dc031)/endProject



### GET Employee Search Result
GET http://localhost:4004/odata/v4/employee/searchEmployees(query='75000')

### GET Employee Order by Salary in DESCENDING ORDER
GET http://localhost:4004/odata/v4/employee/getEmployeesBySalary


### GET Departments having more than two employees using GROUP BY
GET http://localhost:4004/odata/v4/employee/employeesPerDepartment

### GET INNER JOIN - Employees with Department
GET http://localhost:4004/odata/v4/employee/employeeWithDepartment

### LEFT JOIN - GET Emplpoyees with project
GET http://localhost:4004/odata/v4/employee/employeesWithProjects